PACKAGE_NAME = "event";

module.exports = {
  // 刷新team组件
  FRESH_TEAM_COMPONENT: PACKAGE_NAME+"FRESH_TEAM_COMPONENT",
  // 刷新neighbor组件
  FRESH_NEIGHBOR_COMPONENT: PACKAGE_NAME+"FRESH_NEIGHBOR_COMPONENT",
  // 刷新contest组件
  FRESH_CONTEST_COMPONENT: PACKAGE_NAME+"FRESH_CONTEST_COMPONENT",
  // 刷新post页面
  FRESH_POST_PAGE: PACKAGE_NAME+"FRESH_POST_PAGE",
}